---
- hosts: all
  strategy: debug
  vars:
       projectVersion: "{{ projectVersion }}"

  tasks:
   - name: Ensure grafana directory is present
     file:
        path: "{{ deployDir }}"
        state: directory

   - name: Ensure grafana binary is present
     copy:
        src: "deploy/grafana-4.0.0-1480439068.x86_64.rpm"
        dest: "{{ deployDir }}"

   - name: install grafana
     shell: rpm2cpio grafana-4.0.0-1480439068.x86_64.rpm | pax -r -s '/\/usr\/share\/grafana//' -s '/\.\/usr\/sbin/bin/' -s '/\.\/usr\/lib/lib/' -s '/\.\/etc/etc/'
     args:
        chdir: "{{ deployDir }}"

   - name: Ensure templated config-files are created
     template: src={{item.src}} dest={{item.dest}}
     with_items:
        - { src: "deploy/defaults.ini.j2", dest: "{{ deployDir }}/conf/defaults.ini" }
        - { src: "deploy/grafana-supervisor.conf.j2", dest: "{{ deployDir }}/grafana-supervisor.conf" }

   - name: Ensure supervisor conf symlink is updated
     file:
        force: yes
        src: "{{ deployDir }}/{{ projectArtifactId }}-supervisor.conf"
        dest: "{{ supervisorDir }}/{{ projectArtifactId }}.conf"
        state: link

   - name: Ensure supervisor process is restarted
     supervisorctl:
        name: "{{ projectArtifactId }}"
        state: restarted
